### PR TITLE
Check DSM5_crosscutting_adult_schema with psychiatry.org  

### PR DESCRIPTION
**Pull request by ibevers**
Items were checked with:
https://www.psychiatry.org/getmedia/e0b4b299-95b3-407b-b8c2-caa871ca218d/APA-DSM5TR-Level1MeasureAdult.pdf

### CODE REVIEW

**Comment by satra** [comment]
changing the target branch so we can PR the appropriate changes.

**Comment by ibevers** [comment]
@satra I noticed "prefLabel" and item file names all come from the "ELEMENT NAME" column in the file we decided not to use:
Screenshot 2024-04-16 at 10 41 19 AM

Screenshot 2024-04-16 at 10 42 22 AM

Source: [https://nda.nih.gov/data_structure.html?short_name=cde_dsm5crossad01](https://nda.nih.gov/data_structure.html?short_name=cde_dsm5crossad01)

Is this okay? If not, what should I use? The file on www.psychiatry.org just uses numerical labels (e.g. '1', '2', '3'):
Screenshot 2024-04-16 at 10 51 13 AM

Source: 
https://www.psychiatry.org/getmedia/e0b4b299-95b3-407b-b8c2-caa871ca218d/APA-DSM5TR-Level1MeasureAdult.pdf

**Comment by ibevers** [comment]
@satra Additionally, the items are grouped into domains on psychiatry.com: 
Screenshot 2024-04-16 at 10 53 26 AM

Do we want to add a field that contains a label of the domain?

**Comment by ibevers** [comment]
Opening

**Comment by ibevers** [comment]
Note: using ibevers:check-nimh-minimal-schema-activities only for DSM5_crosscutting_adult_schema to scope pull requests to checking individual instruments

**Comment by satra** [comment]
@ibevers - for the first question, preferred label could be a human mnemonic - DSM5 Crosscutting Adult Question 1. there is no clear guidelines, other than a short label that would be easy for a human to interpret.

regarding the second question about the domains, it will be both an item and a compute logic around that item. see the PHQ9 total score as an example in the reproschema-library.

**Comment by satra** [comment]
also the mapping to NDA data elements should be a table based on sssom that we should discuss separately.

**Comment by ibevers** [comment]
@satra, are the files in DSM-5_A/items/ the ones that should be there? I want to confirm before I enter all the information.

**Comment by satra** [comment]
@ibevers - do you mean the domain items. if so yes. perhaps rename the depression one d1_depression. also perhaps the items can be 01, 02 ... so that names (which essentially also become variable names) can be string sorted where possible.

**Comment by ibevers** [comment]
@satra I mean all the files in DSM-5_A/items/. Should I  also have a "dsm5crossad_category" and "dsm5crossad_total_score" item?

**Comment by ibevers** [comment]
@satra the response options used (in valueConstraints), as shown here:
image

 differ from the APA ones:
image

Should "valueConstraints" be updated? Or should the schema reference "dsm5crossad_category"? PHQ-9 has a category item,  which is why I added it.

**Comment by satra** [comment]
valueconstraints should be updated. here i don't think the category item is needed. in phq9, the category is determined based on the total score.

**Comment by ibevers** [comment]
@satra DSM-5-TR does not specify a method for calculating overall scores in this, just domain scores:

https://www.psychiatry.org/getmedia/e0b4b299-95b3-407b-b8c2-caa871ca218d/APA-DSM5TR-Level1MeasureAdult.pdf

Do we want to add a "calculate" field to the domain items that takes the max of the individual items? 

The document says:
"The score on each item within a
domain should be reviewed. Because additional inquiry is based on the highest score on any item within a domain, the
clinician is asked to indicate that score in the “Highest Domain Score” column."

This seems to indicate that the clinician should manually input the domain score, so perhaps "readonlyValue" should be false?

**Comment by satra** [comment]
let's automate this for now.

**Comment by satra** [comment]
there is no `calculate` field for items. the compute specification is in the activity schema. that's where those computations should be added.

**Comment by satra** [comment]
the total score should not be there. as you saw this instrument does not have a total score. (also all of those items need to be updated to reflect that they are part of this assessment, not PHQ-9.

**Review by satra — CHANGES_REQUESTED** [review]
overall, this is looking great. 

1. the domain items need a corresponding value constraint. the current response options is not a responseoptions object. see the existing value constraints object/file and perhaps replicate that for the domain. 
2. the activity schema also needs to add items to addproperties, ui, and isvis (see the phq9 for an example). this will allow these domain items to trigger other forms in a protocol.

relatedly, out of curiosity, are you using the python library to validate these items? and do they pass validation? (you may need to set this up to use the latest PRs that @djarecka and @yibeichan have been working on).

**Comment by ibevers** [comment]
- [ ] Add value constraint for domain items that is a responseoptions object
- [ ] Make the activity schema add items to addproperties, ui, and isvis (see the phq9 for an example)

**Comment by ibevers** [comment]
> relatedly, out of curiosity, are you using the python library to validate these items? and do they pass validation? (you may need to set this up to use the latest PRs that @djarecka and @yibeichan have been working on).

@satra I think it does, assuming I ran the validate command correctly:
Screenshot 2024-04-29 at 11 46 49 AM

**Comment by yibeichan** [comment]
@ibevers the latest validation should be on this branch https://github.com/ReproNim/reproschema-py/tree/ref/linkml @djarecka am I correct?

**Comment by ibevers** [comment]
> @ibevers the latest validation should be on this branch https://github.com/ReproNim/reproschema-py/tree/ref/linkml @djarecka am I correct?

The validate.py on this branch is identical with the master version:
Screenshot 2024-04-29 at 5 34 11 PM

**Comment by yibeichan** [comment]
not that file, here is what i used to validate newly generated schemas, there is a new context file (in this code, it's `reproschema_new`), I believe @djarecka has updated it somewhere
```
from reproschema.model import Protocol, Item, Activity
from reproschema.jsonldutils import to_newformat
import json
import os

activities_dir = "/Users/yibeichen/Desktop/b2ai-redcap2rs/activities"

for subdir, dirs, files in os.walk(activities_dir):

    for filename in files:
    	
        file_path = os.path.join(subdir, filename)

        print(f"Loaded item from: {file_path}")

        data = json.loads(to_newformat(file_path, format="jsonld", contextfile="reproschema_new"))
        del data["@context"]
        
        Item(**data)
```

**Review by satra — APPROVED** [review]
looks good to me. did you run it through the new validator?

**Comment by ibevers** [comment]
Not yet. I wasn't able to find it. I'll ask Dorota and get back to you with the results.

**Comment by satra** [comment]
@djarecka - can you please post a checklist of what's left to do on one of the repos? and a timeline for it. we do need to release asap for both the paper and this work. i also thought that there is a branch that works, no? that @ibevers could use?

**Comment by ibevers** [comment]
Screenshot 2024-05-09 at 6 54 05 PM
New validation passes^^

**Pull request merged**
