### PR TITLE
adding HBN easy-to-convert assessments (12 in total)

### PR DESCRIPTION
**Pull request by yibeichan**
In this PR, I added those easy assessments from HBN. By "easy", I mean (1) no need to compute the subcategories ( see #66 ) and (2) questions in the same assessment have the same value scale.
currently, there are 12 of them:

- [X] ASSQ
- [X] IAT
- [X] PCIAT
- [X] MFQ_P
- [X] MFQ_SR
- [X] CIS_SR
- [X] CIS_P
- [X] SCQ
- [X] ACE 
- [X] ICU_P 
- [X] ICU_SR 
- [X] ARI_P

### CODE REVIEW

**Comment by yibeichan** [comment]
@djarecka can you enable the workflow? thx!

**Comment by satra** [comment]
@yibeichan - when you do the assessments, do check if they are already there and if so update existing one. also for those that can be completed by someone for someone else it would be useful to add that as a set of items instead of creating two separate assessments (unless the questions are different).

**Comment by yibeichan** [comment]
@satra I checked it when I first converted `hbn_asr`, but I didn't add a line to my script to automatically check whether the about-to-be-converted one exists. I will do it.
I have a question about naming those activities. I currently adopted the naming from ABCD, which is `abcd_{assessment_name}`. So for the ones used in HBN, some are specific HBN, and some may be more general. Should I add the prefix `hbn_` or not? 
Also, some activities in `reproschema-library` have uppercase names, but others (especially the abcd ones) have lowercase names.  I'm not aware of a document anywhere that has such details about when I should use uppercases or lowercases (maybe I missed it?).

**Comment by satra** [comment]
the schema name itself does not matter too much since it's just an id. using `hbn_` is fine. the `abcd_` prefix was used since it was converted automatically from NDA schemas. for common activities we were preferring using their standard shortform if available (e.g., PHQ9), but that's not a requirement anywhere.

**Comment by yibeichan** [comment]
okay, I'll keep `hbn_{assessment_name}` since `assessment_name` is from HBN dictionary. for example, ASR means adult self-report, which I don't think is a generalized assessment across studies.

**Comment by yibeichan** [comment]
I'm done with converting easy/simple assessments and have updated the list at the beginning of this PR. Some updates:
1. as a follow-up to the above discussion with @satra, I went to look up the original HBN assessment list and found that some of those assessments have "reference." for those assessments, I treated them as independent of HBN (aka use their own name -> `{assess_name}_schema`). Only for assessments of which `reference==""` or `reference=="Project Developed"`, I name them as `hbn_{assess_name}_schema`. So far, none of the above 12 assessments are HBN-specific.
2. in this new version, I added more detailed `description`, `citation`, `preamble`, and `compute`, for example:
    ```
    "description": "The ASSQ is a 27-item checklist for completion by lay informants when assessing symptoms characteristic of Asperger's Syndrome or high-functioning autism spectrum disorders.",
    "schemaVersion": "1.0.0-rc4",
    "version": "0.0.1",
    "citation": "Ehlers S., Gillberg C., Wing, L. (1999). A screening questionnaire for Asperger\u00a0syndrome\u00a0and other high-functioning autism spectrum disorders in school age children. Journal of Autism Developmental Disorders 29, 129-41.",
    "preamble": null,
    "compute": [
        {
            "variableName": "ASSQ_total_core",
            "jsExpression": "ASSQ_01 + ASSQ_02 + ASSQ_03 + ASSQ_04 + ASSQ_05 + ASSQ_06 + ASSQ_07 + ASSQ_08 + ASSQ_09 + ASSQ_10 + ASSQ_11 + ASSQ_12 + ASSQ_13 + ASSQ_14 + ASSQ_15 + ASSQ_16 + ASSQ_17 + ASSQ_18 + ASSQ_19 + ASSQ_20 + ASSQ_21 + ASSQ_22 + ASSQ_23 + ASSQ_24 + ASSQ_25 + ASSQ_26 + ASSQ_27"
        }
    ],
    ```
3. all my information comes from HBN materials, which may have errors and incomplete info. so a potential problem is that I don't know which part would be erroneous or incomplete unless I manually examine each of them.

**Comment by yibeichan** [comment]
Hi @satra I went through [reproschema doc website](https://www.repronim.org/reproschema/30_schema/#properties-of-reproschema-objects) and [github repo](https://github.com/ReproNim/reproschema/tree/master/terms), don't think there is anything that can be used to indicate `proprietary`.
should we add one to reproschema? if we add something for proprietary assessment, should we also add something for `levels of measurement (categorical, nominal, rank, ratio)` (based on the lab meeting discussion)? or we can add those two one by one, not necessarily simultaneously.

**Comment by yibeichan** [comment]
aha, how about this one [`isAccessibleForFree`](https://schema.org/isAccessibleForFree) from schema.org

**Comment by satra** [comment]
you could just use this `https://schema.org/isProprietary` at the assessment level. it's a simple boolean.

**Comment by yibeichan** [comment]
ah okay, I didn't find it? (i was overthinking I guess. I'll add it and use the csv that maedbh generated to rerun the whole converting thing again.

**Comment by yibeichan** [comment]
okay, I redid those 12 assessments with maedbh's csv (still kept some of my original fields, such as `citation` tho), and also sent PRs to maedbh's repo to fix some minor issues. 
even though all the checks have passed, I do think we (me and @djarecka ) need to go through them one by one before we merge them.

**Comment by yibeichan** [comment]
hello, I finished checking the content part for the following, mostly adding `preamble` and fixing typos. By checking, I mean I found some of those assessments online (see [here](https://drive.google.com/drive/u/2/folders/1W3UBIH900NEEtMn-I4-Bq-ehOAAWEkkn), only SIG people have access), compared the content from those online pdf with the ones provided by HBN, and some adjustment.
so you may notice that SCQ is proprietary that means I could only used the information HBN provided.

- [X] ASSQ
- [X] IAT
- [X] PCIAT
- [X] MFQ_P
- [X] MFQ_SR
- [X] CIS_SR
- [X] CIS_P
- [X] SCQ (proprietary)
- [X] ACE  (TBD)
- [X] ICU_P 
- [X] ICU_SR 
- [X] ARI_P

Here are some questions:
1. how to address skipping logic, for example , in [SCQ_01](https://github.com/yibeichan/reproschema-library/blob/add-hbn-2/activities/SCQ/items/SCQ_01) `"Is she/he now able to talk using short phrases or sentences? If no, skip to question 8."`
2. `ACE` is a bit confusing here. I contact the UCSF person from the reference listed on HBN. And they told me 
    > ACE does not have questions per se, but is a battery of objective measures of cognitive control.  So it is unclear to me how these would be placed into a github repository in any meaningful way. 
    
I might have some miscommunication with the UCSF person, I'll explain to them later. 
also, in the HBN assessment list, this assessment is actually documented as the following. In other words, there is no single assessment called ACE. but we have ACE in the data dictionary from HBN.

| Domain            | Measure                  | Abbreviation(s) COINS                  | Abbreviation(s) LORIS                  | Description                                                                                                                                                                                                                                         | Reference                                                                                                            |
|-------------------|--------------------------|----------------------------------------|----------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------|
| Cognitive Testing | Adaptive Cognitive Evaluation | ACE_Boxed, ACE_BRT, ACE_Flanker, ACE_SAAT, ACE_Spatial_Span_B, ACE_Spatial_Span_F | ACE_Boxed, ACE_BRT, ACE_Flanker, ACE_SAAT, ACE_Spatial_Span_B, ACE_Spatial_Span_F | Mobile cognitive control assessment battery containing standard tests that assess different aspects of cognitive control (attention, working memory, and goal management), modified by incorporating adaptive algorithms, immersive graphics, video tutorials, motivating feedback, and a user-friendly interface. | [Neuroscape Technology](https://neuroscape.ucsf.edu/technology/) |

for next steps: @djarecka I need your help to check the structure, whether we need to add more fields or not. Since all the above assessments were generated by the same script in the first place, they should have the same structure. So you only need to pick one and check it. I would suggest that once we agree on the structure, we merge this PR. If issues come up later, we will fix them in a way that each assessment will have their own PR.

**Comment by satra** [comment]
for skipping logic see the 10th item in phq-9. also phq-9 is an example where the total score itself is an item. for the SCQ that should be added.

for something like ACE, the data elements for the scores can still be added even if the task items are not.

**Comment by yibeichan** [comment]
okay, SCQ fixed, set the skipping logic, and added `SCQ_total_score`. but in general, when should I add the total score to the item? I mean, are there any criteria? If there is a skipping logic, then we add the total score? I notice that PHQ_XXXs have those total scores, but I don't actually know why they have it.

**Comment by satra** [comment]
> I notice that PHQ_XXXs have those total scores, but I don't actually know why they have it.

because each item is a data element, and anything that has a recordable value associated with it should be a defined entity.

**Comment by yibeichan** [comment]
I see, PHQ is a family of assessments, so each of those PHQ_XXXs' total score should be calculated for further computation

**Comment by yibeichan** [comment]
I went back to the reproschema repo and realized that I should add `total_score` for each of those assessments, not only those that are subsets of a family of assessments. So, I revised all those 12 assessments & fixed some typos.

A note to myself: MFQ_SR is a bit weird in that usually, the parent report version and the self report version have the same amount of items that are framed in different ways. But MFQ_SR has only 33 items while MFQ_P has 34 items. This is te information I can get from the HBN dictionary; no full MFQ online was found yet.

**Comment by satra** [comment]
for mfq: https://psychiatry.duke.edu/research/research-programs-areas/assessment-intervention/developmental-epidemiology-instruments-0

**Comment by djarecka** [comment]
I think we should improve the automatic validations of new schemas, but we just reviewed with Yibei and they look similar to others. We made some notes that we want to discuss for the future

**Pull request merged**
