### PR TITLE
[ENH] add Edinburgh handedness inventory

### PR DESCRIPTION
**Pull request by Remi-Gau**
Still work progress.

@mwmaclean might be inerested in adding a few more items.

### TODO

- [x] create an activity with the list of items from the original EHI and a short form version
- [x] add extra items
- [x] check all the translations in French

### CODE REVIEW

**Comment by mwmaclean** [comment]
thanks @Remi-Gau 
Here are the 5 extra items I would be interested in adding:
11. Holding a computer mouse
12. Using a key to unlock a door
13. Holding a hammer
14. Holding a brush or comb
15. Holding a cup while drinking

**Comment by Remi-Gau** [comment]
going from memory and checking what is in there...

- the main activities should correspond the ones listed in the citation field
- there are extra items (some of them should be more appropriate for blind participants)
- I have not added the ones @mwmaclean mentioned

want me to move those extra items to a different folder?

**Comment by satra** [comment]
> there are extra items (some of them should be more appropriate for blind participants)

if these are from the citation they should be added to the same items folder. also multiple activity schemas, if from the same source, (e.g., a separate one for blind individuals) can be created if that is relevant to this assessment.

also the citation refers to the 4 item short form rather than the original edinburgh handedness inventory. so we may indeed want multiple schemas:
- edi-orig
- edi-sf
- edi-blind (i don't know how this is delivered).

**Comment by Remi-Gau** [comment]
Note to self would be nice to finish this one along with refactoring of the doc on the main reproschema repo

**Comment by yibeichan** [comment]
@Remi-Gau helloooo, how's everything going with this PR? :))

**Comment by yibeichan** [comment]
@Remi-Gau my bad... i renamed the branch to `main` and deleted `master`. you can change the PR to `main`

**Pull request closed without merging**
